/**
 * Vendors the pinned Decap CMS runtime out of `node_modules` and into
 * `public/admin/vendor/decap-cms/<version>/`, so `/admin` serves privileged
 * editor JavaScript from this origin instead of a mutable CDN (audit SEC-M1).
 *
 * Why a copy step instead of committing the bundle:
 *
 *   - `decap-cms` is an exact-pinned devDependency, so `package-lock.json`
 *     carries a registry `integrity` hash and `npm audit` sees the package.
 *     The lockfile stays the single source of truth for *which* build ships.
 *   - `decap-cms-manifest.json` is committed and records the version plus a
 *     SHA-256 for every emitted file. That is the reviewable artifact: any
 *     change to the served bytes shows up as a diff in code review, which is
 *     the integrity control that replaces an SRI hash on a CDN tag.
 *
 * Decap's bundle is code-split. webpack derives its `publicPath` at runtime
 * from the `src` of the executing script and requests chunks as
 * `<id>.decap-cms.js` next to it, so the entry and every chunk must land in
 * one directory. Nothing else from `dist/` is needed:
 *
 *   - `*.cms.js`      — the parallel legacy-named build, unused by our entry.
 *   - `*.map`         — source maps; not served (they would publish readable
 *                       source for the admin bundle and add ~50 MB).
 *   - `cms.css`       — belongs to the `cms.js` flavour; Decap injects its own
 *                       styles at runtime, so the entry needs no stylesheet.
 *
 * Usage:
 *   node scripts/vendor-decap.mjs           # write the runtime + manifest
 *   node scripts/vendor-decap.mjs --check   # verify only; non-zero on drift
 */

import { createHash } from "node:crypto";
import { createRequire } from "node:module";
import fs from "node:fs";
import path from "node:path";
import process from "node:process";

const require = createRequire(import.meta.url);
const repoRoot = path.resolve(import.meta.dirname, "..");

/** Files the entry point actually needs: `decap-cms.js` and `<id>.decap-cms.js`. */
const RUNTIME_FILE = /^(?:[0-9]+\.)?decap-cms\.js$/;

const MANIFEST_PATH = path.join(
  repoRoot,
  "public",
  "admin",
  "decap-cms-manifest.json",
);

function sha256(buffer) {
  return `sha256-${createHash("sha256").update(buffer).digest("base64")}`;
}

/** Resolves the installed Decap package directory and its exact version. */
function resolveDecap() {
  const pkgPath = require.resolve("decap-cms/package.json");
  const pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
  const distDir = path.join(path.dirname(pkgPath), "dist");

  if (!fs.existsSync(distDir)) {
    throw new Error(
      `decap-cms is installed but has no dist/ directory at ${distDir}.`,
    );
  }
  return { version: pkg.version, distDir };
}

/** Collects the runtime files, hashed, sorted for a stable manifest. */
function collectRuntime(distDir) {
  const names = fs
    .readdirSync(distDir)
    .filter((name) => RUNTIME_FILE.test(name))
    .sort();

  if (!names.includes("decap-cms.js")) {
    throw new Error("decap-cms/dist/decap-cms.js is missing.");
  }

  return names.map((name) => {
    const bytes = fs.readFileSync(path.join(distDir, name));
    return { name, bytes, integrity: sha256(bytes), size: bytes.length };
  });
}

function buildManifest(version, files) {
  return {
    // Kept human-first: this file is meant to be read in review.
    _comment:
      "Generated by scripts/vendor-decap.mjs. Records the exact self-hosted " +
      "Decap CMS runtime served from /admin. Do not edit by hand; run " +
      "`npm run vendor:decap` after changing the pinned decap-cms version.",
    package: "decap-cms",
    version,
    publicPath: `/admin/vendor/decap-cms/${version}/`,
    entry: "decap-cms.js",
    fileCount: files.length,
    totalBytes: files.reduce((sum, file) => sum + file.size, 0),
    files: Object.fromEntries(
      files.map((file) => [file.name, { integrity: file.integrity, size: file.size }]),
    ),
  };
}

/** Stable JSON so re-running without an upgrade produces no diff. */
function serialize(manifest) {
  return `${JSON.stringify(manifest, null, 2)}\n`;
}

function write(version, files) {
  const outDir = path.join(
    repoRoot,
    "public",
    "admin",
    "vendor",
    "decap-cms",
    version,
  );

  // Remove any previously vendored version so stale chunks cannot be served.
  const vendorRoot = path.join(repoRoot, "public", "admin", "vendor", "decap-cms");
  fs.rmSync(vendorRoot, { recursive: true, force: true });
  fs.mkdirSync(outDir, { recursive: true });

  for (const file of files) {
    fs.writeFileSync(path.join(outDir, file.name), file.bytes);
  }

  fs.writeFileSync(MANIFEST_PATH, serialize(buildManifest(version, files)));

  console.log(
    `Vendored decap-cms@${version}: ${files.length} files ` +
      `(${(files.reduce((s, f) => s + f.size, 0) / 1024 / 1024).toFixed(1)} MB) → ` +
      `public/admin/vendor/decap-cms/${version}/`,
  );
}

/**
 * Verifies the committed manifest against the installed package AND against
 * the files actually on disk. Fails on version drift, byte drift, or a
 * missing/extra file — so a tampered or partially-copied runtime is caught.
 */
function check(version, files) {
  if (!fs.existsSync(MANIFEST_PATH)) {
    throw new Error(
      "public/admin/decap-cms-manifest.json is missing. Run `npm run vendor:decap`.",
    );
  }

  const manifest = JSON.parse(fs.readFileSync(MANIFEST_PATH, "utf8"));
  const problems = [];

  if (manifest.version !== version) {
    problems.push(
      `manifest records ${manifest.version} but node_modules has ${version}`,
    );
  }

  const expected = buildManifest(version, files);
  if (serialize(manifest) !== serialize(expected)) {
    problems.push(
      "manifest does not match the installed package (version, file list, or hashes differ)",
    );
  }

  // The served copy must match the manifest byte for byte.
  const outDir = path.join(
    repoRoot,
    "public",
    "admin",
    "vendor",
    "decap-cms",
    version,
  );
  if (!fs.existsSync(outDir)) {
    problems.push(`vendored runtime is missing at ${path.relative(repoRoot, outDir)}`);
  } else {
    const onDisk = fs.readdirSync(outDir).filter((n) => RUNTIME_FILE.test(n)).sort();
    const declared = Object.keys(expected.files).sort();

    for (const name of declared) {
      if (!onDisk.includes(name)) {
        problems.push(`missing vendored file: ${name}`);
        continue;
      }
      const actual = sha256(fs.readFileSync(path.join(outDir, name)));
      if (actual !== expected.files[name].integrity) {
        problems.push(`hash mismatch for ${name}`);
      }
    }
    for (const name of onDisk) {
      if (!declared.includes(name)) problems.push(`unexpected vendored file: ${name}`);
    }
  }

  if (problems.length > 0) {
    console.error("Decap runtime verification FAILED:");
    for (const problem of problems) console.error(`  - ${problem}`);
    console.error("\nRun `npm run vendor:decap` and review the manifest diff.");
    process.exit(1);
  }

  console.log(
    `Decap runtime verified: decap-cms@${version}, ${Object.keys(expected.files).length} files match the committed manifest.`,
  );
}

const { version, distDir } = resolveDecap();
const files = collectRuntime(distDir);

if (process.argv.includes("--check")) {
  check(version, files);
} else {
  write(version, files);
}
